name: maga
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^8.10.0
  carousel_slider: ^3.0.0
  bubble_tab_indicator: "^0.1.5"
  google_nav_bar: ^5.0.2
  badges: ^1.2.0
  favorite_button: ^0.0.3
  line_icons: ^2.0.0
  curved_navigation_bar: ^0.3.7
  modal_bottom_sheet: ^2.0.0
  transparent_image: ^2.0.0
  flutter_spinkit: "^2.1.0"
  custom_navigator: ^0.3.0
  persistent_bottom_nav_bar: ^4.0.2
  pin_code_fields: ^7.0.0






  community_material_icon: ^5.4.55
  introduction_screen: ^1.0.9
  page_indicator: ^0.3.0
  carousel_pro: ^1.0.0








# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/ff.png
    - assets/image/gn.jpg
    - assets/image/user.png
    - assets/image/splash_1.png
    - assets/image/splash_2.png
    - assets/image/splash_3.png
    - assets/image/burger.jpg
    - assets/image/pasta.jpg

    #......... Burger........

    - assets/image/Elk Burger.jpg
    - assets/image/Cheese Burger.jpg
    - assets/image/Many Burger.jpg
    - assets/image/Onion Burger.jpg
    - assets/image/Uruguay Burger.jpg
    - assets/image/Meat Burger.jpg
    #......... pizza........
    - assets/image/California.jpg
    - assets/image/Chicago.jpg
    - assets/image/Detroit.jpg
    - assets/image/Neapolitan.jpg
    - assets/image/Sicilian.jpg       
    - assets/image/Greek.jpg         
    - assets/image/vegetable pizza.jpg 
   #  .........steak........
    - assets/image/munsell.jpg        
    - assets/image/amirali.jpg 
    - assets/image/menglong.jpg   
    - assets/image/montano.jpg       
    - assets/image/metzer.jpg 
    - assets/image/akash.jpg 
   #  .........Sushi........
    - assets/image/Aburi.jpg
    - assets/image/Maki.jpg
    - assets/image/Temaki.jpg
    - assets/image/oshi.jpg
    - assets/image/markus.jpg
    - assets/image/Gunkan.jpg 
    #  .........pasta........
    - assets/image/Bucati.jpg
    - assets/image/Fettuccine.jpg
    - assets/image/FusiLLni.jpg
    - assets/image/Spaghetti.jpg
    - assets/image/Bucatini.jpg
    - assets/image/Anelli.jpg      
    - assets/image/loading.png   
    - assets/image/fun.png   
    - assets/image/otp.png
    - assets/image/me.jpeg
    
    



     





 




    

    

                             
    




    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lobster-Regular
      fonts:
        - asset: assets/font/Lobster-Regular.ttf
          style: italic
          weight: 500
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
